#!/usr/bin/python3
"""Extract actual r6 mechanics. Run with system Python providing pcbnew."""
from pathlib import Path
import json, hashlib
import pcbnew as p
R=Path(__file__).resolve().parents[2];case=R/'case_r6';src=R/'kicad_r6/amigahid-pico.kicad_pcb'
b=p.LoadBoard(str(src));fs={f.GetReference():f for f in b.GetFootprints()}
def xy(f):return [round(f.GetPosition().x/1e6,4),round(f.GetPosition().y/1e6,4)]
refs=['H1','H2','H3','H4','H5','H6','J1','J3','J4','J5','J6','J7','J9','U1']
data={'pcb_sha256':hashlib.sha256(src.read_bytes()).hexdigest(),'board_mm':[70,68,1.6], 'coordinates':'KiCad X right/Y down; case X=x, Y=68-y','positions':{ref:xy(fs[ref]) for ref in refs},'notch_mm':[10,59,14,9]}
# Connector origin is NOT the centre: use actual shell/contact pads.
for ref in ['J5','J6']:
 pads=[a for a in fs[ref].Pads() if a.GetNumber()=='SH'];assert len(pads)==2
 data[ref+'_centre_x']=sum(a.GetPosition().x for a in pads)/2e6
pads={a.GetNumber():a for a in fs['J4'].Pads() if a.GetNumber()}
data['usb_centre_y']=(pads['1'].GetPosition().y+pads['4'].GetPosition().y)/2e6
(case/'pcb-mechanics.json').write_text(json.dumps(data,indent=2)+'\n')
lines=['// Generated by tools/extract_pcb.py from kicad_r6; units mm.','board_x = 70;','board_y = 68;','board_t = 1.6;']
for ref,coords in data['positions'].items():lines.append(f'{ref.lower()} = {json.dumps([coords[0],68-coords[1]])};')
lines += [f'de9_centres = [{data["J5_centre_x"]}, {data["J6_centre_x"]}];',f'usb_y = {68-data["usb_centre_y"]};']
(case/'pcb-mechanics.scad').write_text('\n'.join(lines)+'\n')
print('Extracted positions, DE9 shell centres and USB contact centre from current PCB.')
